services:
  zookeeper:
    image: bitnami/zookeeper:3.9
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.7
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
    ports:
      - "9093:9093"
    depends_on:
      - zookeeper
    volumes:
      - ./infra/create-topics.sh:/app/create-topics.sh

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    ports:
      - "8085:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    depends_on:
      - kafka

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=expenses
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  expense-service:
    build: ./services/expense-service
    environment:
      - DB_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/expenses
      - KAFKA_BOOTSTRAP=kafka:9092
      - TOPIC_EXPENSES_RAW=expenses.raw
      - TOPIC_EXPENSES_PARSED=expenses.parsed
    ports:
      - "8001:8001"
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started

  ml-service:
    build: ./services/ml-service
    environment:
      - KAFKA_BOOTSTRAP=kafka:9092
      - TOPIC_EXPENSES_RAW=expenses.raw
      - TOPIC_EXPENSES_PARSED=expenses.parsed
      - HF_MODEL=sentence-transformers/all-MiniLM-L6-v2
    ports:
      - "8002:8002"
    depends_on:
      kafka:
        condition: service_started

  api-gateway:
    build: ./services/api-gateway
    environment:
      - EXPENSE_SERVICE_URL=http://expense-service:8001
    ports:
      - "8000:8000"
    depends_on:
      - expense-service

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - api-gateway
