name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [expense-service, ml-service, api-gateway]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r services/${{ matrix.service }}/requirements.txt
          pip install pytest
          # Needed for expense-service to use SQLite in tests
          if [[ "${{ matrix.service }}" == "expense-service" ]]; then
            pip install aiosqlite
          fi

      - name: Run unit tests
        env:
          # Make "from app ..." imports resolve to the service's folder
          PYTHONPATH: ${{ github.workspace }}/services/${{ matrix.service }}
          # Use in-memory SQLite for tests (no Postgres/Alembic)
          DB_URL: "sqlite+aiosqlite:///:memory:"
        run: |
          echo "Running unit tests for ${{ matrix.service }}..."
          if [[ "${{ matrix.service }}" == "api-gateway" ]]; then
            echo "No tests for api-gateway yet; marking as success."
            exit 0
          fi
          pytest -v -k "not integration" services/${{ matrix.service }}/tests

