name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [expense-service, ml-service]

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testdb
        ports: ["5432:5432"]
        options: >-
          --health-cmd "pg_isready -U user -d testdb"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: services/${{ matrix.service }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install alembic psycopg2-binary pytest

      - name: Run migrations (if Alembic present)
        working-directory: services/${{ matrix.service }}
        env:
          DATABASE_URL: postgresql+psycopg2://user:password@localhost:5432/testdb
        run: |
          if [ -f alembic.ini ]; then
            alembic upgrade head
          fi

      - name: Run tests
        working-directory: services/${{ matrix.service }}
        env:
          DATABASE_URL: postgresql+psycopg2://user:password@localhost:5432/testdb
        run: |
          pytest -q

